### ISSUE TITLE
help please... i am trying to use this with whatever sample i have but i got this error every single time.

### ISSUE THREAD

**Issue by oilbugxx** [the-database/AnimeJaNaiConverterGui#19]
Generating TensorRT engine with command: ..\..\VSPipe.exe -c y4m --arg "slot=1" --arg "video_path=D:\[Trix] Heavenly Delusion - AV1 MiNi\[Trix] Heavenly Delusion S01E01 (BD 720p AV1) [96B45EE1].mkv" --start 0 --end 1 ./animejanai_encode.vpy -p .
Script evaluation failed:
Python exception: Source: No video track found
Traceback (most recent call last):
  File "src\\cython\\vapoursynth.pyx", line 3124, in vapoursynth._vpy_evaluate
  File "src\\cython\\vapoursynth.pyx", line 3125, in vapoursynth._vpy_evaluate
  File "./animejanai_encode.vpy", line 19, in <module>
    clip = vs.core.ffms2.Source(source=args["video_path"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\\cython\\vapoursynth.pyx", line 2860, in vapoursynth.Function.__call__
vapoursynth.Error: Source: No video track found
Upscaling with command: ..\..\VSPipe.exe -c y4m --arg "slot=1" --arg "video_path=D:\[Trix] Heavenly Delusion - AV1 MiNi\[Trix] Heavenly Delusion S01E01 (BD 720p AV1) [96B45EE1].mkv" ./animejanai_encode.vpy - | ffmpeg  -i pipe: -i "D:\[Trix] Heavenly Delusion - AV1 MiNi\[Trix] Heavenly Delusion S01E01 (BD 720p AV1) [96B45EE1].mkv" -map 0:v -c:v libx265 -crf 16 -preset slow -x265-params "sao=0:bframes=8:psy-rd=1.5:psy-rdoq=2:aq-mode=3:ref=6" -map 1:t? -map 1:a?  -map 1:s? -c:t copy -c:a copy -c:s copy "B:\[Trix] Heavenly Delusion S01E01 (BD 720p AV1) [96B45EE1]-animejanai.mkv"
ffmpeg version 2024-03-07-git-97beb63a66-essentials_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --pkg-config=pkgconf --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-dxva2 --enable-d3d11va --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58. 40.100 / 58. 40.100
  libavcodec     60. 41.100 / 60. 41.100
  libavformat    60. 25.100 / 60. 25.100
  libavdevice    60.  4.100 / 60.  4.100
  libavfilter     9. 17.100 /  9. 17.100
  libswscale      7.  6.100 /  7.  6.100
  libswresample   4. 14.100 /  4. 14.100
  libpostproc    57.  4.100 / 57.  4.100
Script evaluation failed:
Python exception: Source: No video track found
Traceback (most recent call last):
  File "src\\cython\\vapoursynth.pyx", line 3124, in vapoursynth._vpy_evaluate
  File "src\\cython\\vapoursynth.pyx", line 3125, in vapoursynth._vpy_evaluate
  File "./animejanai_encode.vpy", line 19, in <module>
    clip = vs.core.ffms2.Source(source=args["video_path"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\\cython\\vapoursynth.pyx", line 2860, in vapoursynth.Function.__call__
vapoursynth.Error: Source: No video track found
[in#0 @ 000001cff85c0500] Error opening input: Invalid data found when processing input
Error opening input file pipe:.
Error opening input files: Invalid data found when processing input

**Comment by oilbugxx** [comment]
sorry, nevermind, it actually work with hevc now somehow, i remember that it didnt before.
